### ISSUE TITLE
Operator installation via ArgoCD

### ISSUE THREAD

**Issue by selfuryon** [VictoriaMetrics/operator#255]
Hello!
I have an issue with vm operator installation via ArgoCD: vm operator creates resources such as `service-account` per `VMalert`/`VMSingle`/`VMAgent`/`VMAlertmanager` and also creates `cluster role` and `cluster role binding` for each vmagent, but it also adds all annotations from CR to all resources it created.
As result, ArgoCD see that it manages these resources (because of annotations), but there are no manifests in source repo and these resources don't have ownerReferences to resources managed by ArgoCD, so it decides to prune these resources.

![image](https://user-images.githubusercontent.com/2993917/121372471-fb8abf80-c946-11eb-928c-8c10d01e1223.png)

So there are several roots of this issues:
* Resources haven't ownerReferences
* Cluster Resources are created via specific namespace-scoped CR

Example solution:
* Create one `cluster role` and `cluster role binding` (and use only one for all vmagents) via helm chart not by operator per vmagent
* Set ownerReferences for `service accounts` to CR

I also link this to ArgoCD issue: https://github.com/argoproj/argo-cd/issues/4487

**Comment by f41gh7** [comment]
Thanks for reporting. Biggest challenge here - ownerReference for CR and CRB, according to kubernetes docs:

```
Cluster-scoped dependents can only specify cluster-scoped owners. In v1.20+, if a cluster-scoped dependent specifies a namespaced kind as an owner, it is treated as having an unresolveable owner reference, and is not able to be garbage collected.
```

 need to investigate it. For dependent objects are deleted by operator. Probably, it can be ignored for our case.

**Comment by f41gh7** [comment]
@selfuryon , i've added ServiceAccount ownerReference. 

 Btw, i wasn't able to reproduce Out-Of-Sync status for PSP and CR. Can you share information or some example how to achieve it? 

  Probably, it was fixed at latest version of ArgoCD?

**Comment by xom4ek** [comment]
Same issue.

Create repo with only one file and create application in argo

Chart.yaml
```
apiVersion: v1
name: monitoring
version: 1.0.0
appVersion: 1.0.0
description: meta chart for monitoring
dependencies:
- name: victoria-metrics-k8s-stack
  repository: "https://victoriametrics.github.io/helm-charts/"
  version: "1.6.2"
```

![image](https://user-images.githubusercontent.com/29627495/124348598-7320d700-dbf3-11eb-9277-573041c82f75.png)

**Comment by f41gh7** [comment]
@xom4ek  cannot reproduce ( works for me.

 I'm using latest argoCD version with chart:
```yaml
apiVersion: v1
name: monitoring
version: 1.0.0
appVersion: 1.0.0
description: meta chart for monitoring
dependencies:
- name: victoria-metrics-k8s-stack
  repository: "https://victoriametrics.github.io/helm-charts/"
  version: "0.2.8"
  appVersion: "1.16.0"

```

**Comment by selfuryon** [comment]
Hello!
I upgraded ArgoCD and VM Operator and I see that secret issues are gone, but cluster role and cluster role binding are still present.
My ArgoCD version:
```
{
    "Version": "v2.0.4+0842d44",
    "BuildDate": "2021-06-23T01:27:53Z",
    "GitCommit": "0842d448107eb1397b251e63ec4d4bc1b4efdd6e",
    "GitTreeState": "clean",
    "GoVersion": "go1.16",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.9.4 2021-02-09T19:22:10Z",
    "HelmVersion": "v3.5.1+g32c2223",
    "KubectlVersion": "v0.20.4",
    "JsonnetVersion": "v0.17.0"
}
```
My application:
```
metadata:
  name: msk-vm-operator
  namespace: argocd
  labels:
    kind: service-apps
spec:
  source:
    repoURL: https://victoriametrics.github.io/helm-charts
    targetRevision: 0.1.15
    helm:
      version: v3
      releaseName: victoriametrics
      values: |
        operator:
          psp_auto_creation_enabled: false
    chart: victoria-metrics-operator
...
kind: Application
apiVersion: argoproj.io/v1alpha1
```
My manifests:
```
spec:
  image:
    tag: v1.61.1
  retentionPeriod: 2d
  removePvcAfterDelete: true
  logFormat: json
  storage:
    accessModes:
    - ReadWriteOnce
    storageClassName: ***
    resources:
      requests:
        storage: 20Gi
metadata:
  name: msk
  namespace: vm-operator
kind: VMSingle
apiVersion: operator.victoriametrics.com/v1beta1
---
metadata:
  name: msk
  namespace: vm-operator
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous                     
    argocd.argoproj.io/sync-options: Prune=false
spec:
  image:
    tag: v1.61.1
  serviceScrapeNamespaceSelector: {}
  podScrapeNamespaceSelector: {}
  podScrapeSelector: {}
  serviceScrapeSelector: {}
  nodeScrapeSelector: {}
  nodeScrapeNamespaceSelector: {}
  staticScrapeSelector: {}
  staticScrapeNamespaceSelector: {}
  replicaCount: 1
  logFormat: json
  externalLabels:
    site: msk
    kind: kubernetes
    cluster: msk
  remoteWrite:
  - url: http://vmsingle-msk:8429/api/v1/write
  resources:
    limits:
      cpu: "1"
      memory: 2000Mi
    requests:
      cpu: 500m
      memory: 1000Mi
kind: VMAgent
apiVersion: operator.victoriametrics.com/v1beta1
---
spec:
  image:
    tag: v1.61.1
  replicaCount: 1
  datasource:
    url: http://vmsingle-msk:8429
  remoteWrite:
    url: http://vmsingle-msk:8429
  remoteRead:
    url: http://vmsingle-msk:8429
  notifier:
    url: http://vmalertmanager-msk:9093
  evaluationInterval: 30s
  ruleNamespaceSelector: {}
  ruleSelector: {}
  logFormat: json
  extraArgs:
    external.alert.source: explore?orgId=1&left=["now-1h","now","msk",{"exemplar":true,"expr":"{{$expr|quotesEscape|crlfEscape|queryEscape}}"}]
    external.url: ***
metadata:
  name: msk
  namespace: vm-operator
kind: VMAlert
apiVersion: operator.victoriametrics.com/v1beta1
---
spec:
  image:
    tag: v0.22.0
  externalURL: ***
  replicaCount: 1
  configSecret: msk-alertmanager
  logFormat: json
  resources:
    limits:
      cpu: 200m
      memory: 400Mi
    requests:
      cpu: 50m
      memory: 200Mi
metadata:
  name: msk
  namespace: vm-operator
kind: VMAlertmanager
apiVersion: operator.victoriametrics.com/v1beta1
```
As temporal fix I used these annotations for VMAgent CR:
```
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous                     
    argocd.argoproj.io/sync-options: Prune=false
```
![image](https://user-images.githubusercontent.com/2993917/124575765-5800d200-de54-11eb-9395-872eae26c207.png)
![image](https://user-images.githubusercontent.com/2993917/124575816-6353fd80-de54-11eb-95ed-ced73ff7c737.png)

**Comment by f41gh7** [comment]
For some reason, my argoCD installation cannot detect `Clusterrole`, `ClusterRoleBinding` and `PodsecurityPolicy` for `VMAgent`, `VMAlert` and `VMSingle`. And it reports app status as synced.

**Comment by selfuryon** [comment]
Do you manage this CRs via ArgoCD?

**Comment by f41gh7** [comment]
Yep, my manifests:

https://github.com/f41gh7/api-tests/blob/master/components/manifests.yaml

**Comment by selfuryon** [comment]
Can you add `VMAgent`? My `ClusterRoleBinding` and `Clusterrole` are created by VM Operator for `VMAgent`.

**Comment by f41gh7** [comment]
No luck, 

  My  deployment:

https://i.imgur.com/smApNPy.png

**Comment by selfuryon** [comment]
So strange :) I noticed, that I also have this option in argocd-cm:
```
application.instanceLabelKey: sp.corp/managed-by
```
So when I add vmagent, it also has this label (it's expected). ArgoCD uses it for tracking resources:
![image](https://user-images.githubusercontent.com/2993917/124599506-6a880500-de6e-11eb-9785-95b100d2a18f.png)
So before apply I see vmagent like this:
![image](https://user-images.githubusercontent.com/2993917/124599649-92776880-de6e-11eb-83c9-41450de16031.png)
After applying I see this:
![image](https://user-images.githubusercontent.com/2993917/124599738-ac18b000-de6e-11eb-9c90-bc0799bfcdb3.png)
So vmagent become to Ok, but there a new CR are created in ArgoCD. If we inspect it we will see this:
![image](https://user-images.githubusercontent.com/2993917/124599991-f39f3c00-de6e-11eb-942d-9411baa054d6.png)
Because Argocd uses this label for tracking it see these resources.
So maybe VM-Operator blocks the default label (`argocd.argoproj.io/instance`?!) for ArgoCD (as example, it can explain why you don't have any problem) but I don't use it and that's why I have this issue?

**Comment by f41gh7** [comment]
Thanks, get it. Was able to reproduce.

**Comment by f41gh7** [comment]
Now operator adds correct ownerReference to the clusterScope objects, it can be tested with docker image:
`victoriametrics/operator:fixes-argo-cd-deployment`. Operator requires additional permissions for it:

```yaml
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
  verbs:
    - get
    - list
```

**Comment by selfuryon** [comment]
Awesome! Looking forward to trying it in next VM Operator release!

**Comment by xom4ek** [comment]
Seems okay for vmCRDs only in monitoring applications but for another applications with PodMonitors/ServiceMonitors problem still here:
![image](https://user-images.githubusercontent.com/29627495/124951248-d78ccd80-e01b-11eb-8b3c-3104c261172c.png)
![image](https://user-images.githubusercontent.com/29627495/124951288-e07d9f00-e01b-11eb-81f3-0823cb23c4f2.png)


For reproduce:
Values.yaml for vm-operator:
```yaml
  victoria-metrics-operator:
    image:
      tag: fixes-argo-cd-deployment
    operator:
      disable_prometheus_converter: false
```

And just another application (nginx-ingress for example) with ServiceMonitor CRD:

Chart.yaml
```yaml
apiVersion: v2
name: ingress-nginx
version: 1.0.0
appVersion: 1.0.0
description: meta chart for ingress-nginx
dependencies:
- name: ingress-nginx
  repository: "https://kubernetes.github.io/ingress-nginx"
  version: "3.33.0"
```
Values-nginx.yaml
```yaml
ingress-nginx:
  controller:
     metric:
       serviceMonitor: 
         enabled: true
```

**Comment by xom4ek** [comment]
@f41gh7 Test your tag for vmoperator - everything work fine)

But now problem with pvc for vmsingle (clusterrole outOfSync becouse add new permissions):
![image](https://user-images.githubusercontent.com/29627495/124953688-09069880-e01e-11eb-9fe6-59a252ee18e9.png)

**Comment by f41gh7** [comment]
hm, i think, thaat vmsingle's pvc ownership can be fixed with `removePvcAfterDelete` option for `VMSingle`.

```
vmsingle:
  spec:
    removePvcAfterDelete: true
```

**Comment by xom4ek** [comment]
Yes, that helped, thanks!

**Comment by selfuryon** [comment]
I have just updated our current VM operator to the latest version (0.1.16) and all works fine. 
Thank you for resolving this issue
